### ISSUE TITLE
Store uploaded report in memory storage

### ISSUE THREAD

**Issue by celmoussaoui** [wearefrank/ladybug-frontend#316] opened 2023-07-10 14:07 UTC
As of now, we cannot apply the different views (white, grey, black) to uploaded reports, while the old GUI does provide this feature.

**Comment by jacodg** [comment] 2024-10-31 17:11
Duplicate of https://github.com/wearefrank/ladybug-frontend/issues/310 I suppose

**Closed by jacodg** 2024-10-31 17:11 UTC
Labels: Frontend, Backend
